### ISSUE TITLE
Change in face-tracker documentation snippet

### ISSUE THREAD

**Issue by mihirm3hub** [zappar-xr/zappar-aframe#20]
The documentation snippet for zappar-visible & zappar-not visible events in the face tracking section have a small correction,
`<a-entity zappar-face id="my-face-tracker">
  
</a-entity>

<script>

let myFaceTracker = document.getElementById("my-image-tracker");

myFaceTracker.addEventListener("zappar-visible", () => {
  console.log("Face has become visible");
});

myFaceTracker.addEventListener("zappar-notvisible", () => {
  console.log("Face is no longer visible");
});

</script>
`
The let myFaceTracker = document.getElementById("my-image-tracker"); 
needs to be changed to 
"let myFaceTracker = document.getElementById("my-face-tracker");"

**Comment by nyan-left** [comment]
Hey, thanks for noting down the mistake. Will fix next patch :)
